### ISSUE TITLE
brillouine zone is on going?

### ISSUE THREAD

**Issue by tkotani** [giovannipizzi/seekpath#8]
I like you will include variety of samples in the package.
Anyway I can not yet plot my own BZone.

Please, not set ax.axis('off').
And I hope you use ax.set_aspect('equal') to keep the same aspect ratio.

**Comment by giovannipizzi** [comment]
Hi,
are you speaking of the web interface? What do you mean exactly with "I cannot plot my own BZone"? Do you get an error message or the result is not the expected one? Can you provide an example input?

For the axes, the three x,y,z axes are shown as arrows - is this not enough for you? What would you like to see?

For the aspect ratio: yes, it is not stretched, but note that by default I use a perspective view, that can be maybe unintuitive at first (but I think makes it easier to understand the shape for very regular shapes, because it reduces the overlaps of edges of different faces).

Let me know what is the exact issue you have with the BZ, otherwise I will close this issue.

**Comment by tkotani** [comment]
I examined your code and slight modification for my purpose.
It seems no problem now. I can use matplotlib to plot BZ well. 
Thank you.
